### ISSUE TITLE
Are you considering building another lib to support dynamic (real-time) rates?

### ISSUE THREAD

**Issue by mohamedhayibor** [Tahler/currency-rs#4]
This is not an issue, really. Awesome job on writing the library. Learned quiet a bit in reading the way you implemented it.

If you ever consider dynamic prices this might be a good resource: https://openexchangerates.org/quick-start

**Comment by Tahler** [comment]
Hi, glad to hear you're interested in the library and thanks for the compliment :)
Believe it or not, I've looked into this feature and I actually have that exact site bookmarked for later!
I still have plenty more work planned for this library, especially with more reliable accuracy, but I'm super booked with school work at the moment. I should be able to start working on this again in about 6 weeks.
